### ISSUE TITLE
Unable to run the application on kvm

### ISSUE THREAD

**Issue by Shariar076** [unikraft/app-python3#1]
I tried running the application on my KVM, using `kraft up -m x86_64 -p kvm python3`. Which resulted in the following:

[    2.448547] ERR:  [libuksched] sched.c @ 146  : Failed to allocate thread stack
[    2.452517] CRIT: [libukboot] boot.c @ 267  : Could not create main thread

The full form:
2020-04-23 00:47:15 INFO     Using networking bridge 'net0'
2020-04-23 00:47:15 INFO     Starting network services...
SIOCSIFADDR: Operation not permitted
SIOCSIFFLAGS: Operation not permitted
2020-04-23 00:47:15 INFO     Starting dnsmasq...
/home/himel/.local/bin/kraft-net: line 152: /var/log/dnsmasq-net0.log: Permission denied
2020-04-23 00:47:15 INFO     dnsmasq runninig with pid: 16363
Trying to get root privileges...
**************************************************************************
 QEMU:
   Name:                  d54f70fb-100a-4f38-ae31-abc80a8c1ff6
   PID:                   16388
   Monitor socket:        /run/qemu-guest-16368_monitor.socket
   VNC listen:            5900

   SMP configuration:     sockets=1,cores=1,threads=1
   Memory:                64 MB
   Kernel:                /home/himel/Unikraft-kernels/python3/build/python3_kvm-x86_64
   Parameters:            vfs.rootdev=fs0 vfs.rootfs=9pfs -- "helloworld.py"

   Warning: Guest will be terminated with CTRL+C!
**************************************************************************
Starting VM...
Connecting to serial output...

Google, Inc.
Serial Graphics Adapter 03/05/17
SGABIOS $Id: sgabios.S 8 2010-04-22 00:03:40Z nlaredo $ (generic@generic) Sun, 05 Mar 2017 16:09:17 +0100
Term: 169x36
4 0
SeaBIOS (version 1.10.2-1ubuntu1)
iPXE (http://ipxe.org) 00:03.0 C100 PCI2.10 PnP PMM+03F8DAD0+03ECDAD0 C100
                                                                              
Booting from ROM...
[    2.542433] ERR:  [libuksched] sched.c @ 146  : Failed to allocate thread stack
[    2.546169] CRIT: [libukboot] boot.c @ 267  : Could not create main thread

**Comment by nderjung** [comment]
Hi, looks like you're running out of memory!

Try again with:
```
kraft run -m x86_64 -p kvm -M 512
```
